version: "3"
services:
  gitlab-mysql:
    container_name: gitlab-mysql
    restart: always
    image: sameersbn/mysql:latest
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
    volumes:
      - ./volumes/gitlab/mysql:/var/lib/mysql
  gitlab:
    container_name: gitlab
    restart: always
    image: sameersbn/gitlab:latest
    environment:
      - DEBUG=false
      - TZ=Asia/Tokyo
      - DB_HOST=gitlab-mysql
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - TZ=Asia/Tokyo
      - GITLAB_TIMEZONE=Tokyo
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_HOST=
      - GITLAB_PORT=
      - GITLAB_SSH_PORT=
      - GITLAB_RELATIVE_URL_ROOT=/gitlab
      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false
      - GITLAB_EMAIL=notifications@example.com
      - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com
      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00
      - SMTP_ENABLED=false
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login
      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false
    volumes:
      - ./volumes/gitlab/gitlab:/home/git/data
  gitlab-redis:
    container_name: gitlab-redis
    restart: always
    image: sameersbn/redis:latest
    volumes:
      - ./volumes/gitlab/redis:/var/lib/redis
  redmine-mysql:
    container_name: redmine-mysql
    restart: always
    image: sameersbn/mysql:latest
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
    volumes:
      - ./volumes/redmine/mysql:/var/lib/mysql
  redmine:
    container_name: redmine
    restart: always
    image: sameersbn/redmine:latest
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=redmine-mysql
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
      - REDMINE_PORT=
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=/redmine
      - REDMINE_SECRET_TOKEN=
      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15
      - REDMINE_CONCURRENT_UPLOADS=2
      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=
      - SMTP_ENABLED=false
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login
      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30
    volumes:
      - ./volumes/redmine/redmine:/home/redmine/data
  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - redmine
      - gitlab
    networks:
     - my_network
networks:
  my_network:
