version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
    volumes:
      - ./volumes/redmine/postgresql:/var/lib/postgresql
    restart: always

  redmine:
    image: sameersbn/redmine:3.4.2
    depends_on:
      - postgresql
    restart: always
    environment:
      - TZ=Asia/Tokyo 

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

      - REDMINE_PORT=10443
      - REDMINE_HTTPS=true 
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=daily
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=
      - SMTP_HOST= 
      - SMTP_PORT=25 
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_STARTTLS=false
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - ./volumes/redmine/redmine:/home/redmine/data
